# Generated by Django 5.0.6 on 2024-06-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Article picture - Картинка')),
                ('title', models.CharField(max_length=256, verbose_name='Title - Заголовок')),
                ('body', models.CharField(max_length=10000, verbose_name='Main body - Содержание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created - Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated - Обновлено')),
            ],
        ),
    ]
