# Generated by Django 5.0.6 on 2024-06-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer_alter_article_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
